sonar.projectKey=Vivien-PARSIS-Tasklist-Frontend
sonar.coverage.exclusions=src/App.tsx,src/main.tsx,src/__tests__/*.ts,src/__tests__/*.tsx,src/hooks/useTasks.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info